splashes = {
    "Well done. Here are the test results:\nYou are a horrible person.\nI'm serious, that's what it says: A horrible person.",
    "Hehe Lois im an orbital strike cannon",
    "Edit the editbox.\nDO IT\n(don't forget about pressing Enter key!)",
    "Eat the editbox.\nDON'T DO IT, IT'S POISONOUS",
    "Whatever",
    "Today's your lucky day!",
    "Who wants to become a bullet sponge?",
    "This cannon is now canon!\n(to this universe)",
    "Why is there even a slider\nin the first place?",
    "h",
    "PanzerShrek.\nWhy shrek though?",
    "HEAT is soon to come.\nJust need to steal some documents first.",
    "SplashText.txt",
    "Please, not the 1000mm HE!",
    "Previous splash was lying.",
    "owo",
    "I like bullets",
    "All jokes and games until the projectile\nglitches right through your armor.",
    "let me out let me out let me out let me out let me out let me out let me out let me out let me out let me out let me out\n  let me out let me out this is a joke btw let me out let me out let me out let me out let me out let me out let me out let me out\n let me out let me out let me out let me out let me out let me out let me out let me out let me out let me out let me out\n",
    "What's the agenda for today?",
    "This is a false sentence.\n(POWERED BY CAPTCHA)",
    "Artificial Intelligence?\nNah, I prefer natural stupidity",
    "Fully organic!",
    "!11?41??!1!",
    "LEROY JENKINS",
    "Ferrium was here",
    "...but nobody came",
    "Undertale, amiright?",
    "No italic?\nNo bold either?\nThis sucks on ice.",
    "THINK FAST CHUKLENUTS",
    --"#e81416r#ffa500a#faeb36i#79c314n#487de7b#4b369do#70369dw #e81416t#ffa500o#faeb36a#79c314s#487de7t#4b369de#70369dr",
    "Mr. President, the towers have been tomfoolered",
    "This splash screen may or may not\ncontain offensive jokes.",
    "www.youtube.com/watch?v=8ybW48rKBME",
    ":trollface:",
    "In my medical opinion?\nYOU'RE DEAD!",
    "It is good day to be\nNOT\nDEAD!",
    "My condolences to your -less than-\nfullHD monitor text scaling",
    "Make the tank you wish\nto see in real life!",
    "Totally not War Thunder advertisement",
    "Wuh oh",
    "Make this a splash pls",
    "500mm BESH hits different at 3am",
    "HE moment",
    "Hey, my caliber is up here!",
    "How do you pronounce #4b369dDonity_Qramixy?",
    "Ferrium was Ferry before.\nI changed it because it was too similar to Furry.\nNo hate though",
    "Ferrarium\nwroom wroom mothafaka",
    "I-It's too big!\n>=<",
    "I may be offensive..\nBut I do love yall",
    "No HE in the building!",
    "hehe shell go boom",
    "APHE actually works.\n(It fried my code AND my brain)",
    "-Insert rickroll here-",
    "What does the tank say?",
    "You've been APFSDS'd",
    "Oh boy, i sure do hope\nthat no flying piece of metal\n ruins my day today!",
    "Come back later,\nand maybe I will tell you a story?",
    "Exotic butters",
    "Go play Voices of the Void.\nIt's FREE",
    "Roblox Cursed Tank Simulator, War Thunder, GHPC...\nCouldn't this mod be more original?",
    "Water gun",
    "Be careful with recoil,\nthe cannons are NOT recoilless!",
    "64th splash!",
    "Go play War Thunder!",
    "Scrap Mechanic sux",
    "Yeah yeah, Logic (the modder)..\nI know you're here.",
    "Teh cannns ar dangerus!",
    "Waiter, waiter!\nMore lua hooks please!",
    "English wasn't my first language,\nEngrish was",
    "[REDACTED]",
    "My monitor fell",
    "My keyboard flipped",
    "My mouse disconnected",
    "My gpu fell off",
    "Where's my cpu cooler",
    "empty",
    "Previous splash was telling the truth!",
    "You unboxed a #4b369dRare!",
    "No spreading hate!\nOnly fast flying lead!",
    "Sitting here for splash screens, huh?",
    "Gunner, HEAT, PC!",
    "Exclusive to breech GUI",
    "Now vanilla flavoured!",
    "GUI scaling sux",
    "Censor?\nWhy suck the fun out of everything?",
    "tee-hee",
    "The 2nd amendment rights, officer!",
    "Locked & Loaded!",
    "That tank was already ablaze when I got here,\nI swear!",
    "Look around, maybe you'll find something\nmore important to do than this",
    "Boykisser cannon warning ^^",
    "FUNNY GUY!\nRIGHT HER-\n-AAAAAAAAAAH",
    "explosion\nsound\nxddddddddddddd",
    "no more funni 4 u",
    "objectively the best part of this mod\nchange my mind",
    "Wasted potential imo",
    "Haha, I have a debug tool for showing projectile paths\nAND YOU DON'T!",
    "These AP shells are powered by\n...\nSNAPPING TURTLES! yes, turtles! I am not lying!",
    "A few inches later...",
    "Warship?\nLandship!",
    "Just in case, don't put the raccoons in APHE shells.",
    "Breathing is now a felony!",
    '"offensive"',
    --"fuk u\nnot you, im talking to the person behind you!",
    "Mistakes were made.",
    "Опа, русский?",
    "Go get 'em",
    "lulz",
    "When the update comes,\n(IF it comes)\nI will add custom sounds!",
    "Did you know?\n1981 was the year that",
    "WHAT THE DUCK IS A MILLIMETERRRRRRRRRR",
    "rawr",
    "u furry",
    "'english alphabet'",
    "Tem shop will never be the same",
    "Cmon, Ae!",
    "Crank it to the max!",
    "Next time someone screams 'unfair' -\nscream at them back!",
    "After all...\nWhy not?\nWhy not use 4mm APFSDS?",
    "Geneva convention?\nNever heard of her.",
    --"'Caliber is just a number'\n- some dude I saw on the Internet",
    "Explode the bridges!\n(and the world)",
    "hi scrapman",
    "goofy ahh skibidi toilet rizz sigma breech\nonly in ohio fanum tax shells\nmewing skibidi tank fr",
    "You are my sunshine\nMy only sunshine",
    "Don't overheat your gun!\nOtherwise it'll have mild fever.",
    "Peter Tank",
    "Peter Helicopter",
    "Boom, goes the tank!",
    "Whoosh, goes the turret!",
    "Recoil is like a rocket thruster -\n- both operate on the same principle!",
    "Shell goes in the breech!",
    "Autocannons are NOT the usual breeches!\nAnd I don't care about what anyone says!",
    "Hehe 10000 lines of code",
    "Look Lois im a large mod",
    "Fortune cookie says...",
    "Ppl will probably like this splash screen\nmore than the mod itself... GOOD!",
    "Hey, I can make money off of this!",
    "Shoot me once, shame on me.\nShoot me twice - im the unluckiest here",
    --"I took a shit in the toilet,\nask me questions.",
    --"dushaman gay",
    --"dushaman milfhunter",
    "Ooh you like guns\nYou are a gunkisser!",
    "fart gun",
    "Is it even placed on a tank?",
    "Time to commit minor trollage",
    "Are you team APFSDS or team HE?\nDoesn't matter, both good.",
    "APHE? Did someone sneeze?",
    "Learn your ABC's",
    "Caught me off guard, sry",
    "BESH FOREVER",
    "hi",
    "hiii",
    "hiiiiiiiiiiiiiiii",
    "This probably slaps.",
    "Let me be clear,\ncannon breeches aren't edible.",
    "How 'bout you make\nthe caliber lower?",
    "What's the plan?",
    "How's it going?",
    "Big or small cannon today?",
    "Whatcha doin'?",
    "Nice cannon you have!",
    "Time to mix some things up, huh?",
    "Nice to see you again.",
    "What brings you here today?",
    "Got the caliber and fire delay sliders,\nwhich one you want?",
    "Funny slider go woosh",
    "Better than throwing a pebble!",
    "Probably here to check up on me again, right?",
    "Nothing to see here!",
    "mmm cheezeburger",
    "Coca-Cola or Pepsi?",
    "Tank, Ship or Plane\n- Doesn't matter -\nBreech's still the same!",
    "Horrifying reality of tank warfare\nneatly packaged into a mod\nfor a toony game.",
    "I'm hungry for some tungsten!",
    "Tungsten cube or APFSDS?\nChoice is yours."
}
