splashes = {
    "Well done. Here are the test results:\nYou are a horrible person.\nI'm serious, that's what it says: A horrible person.",
    "Hehe Lois im an orbital strike cannon",
    "Edit the editbox.\nDO IT",
    "Eat the editbox.\nDON'T DO IT, IT'S TOXIC",
    "Whatever",
    "Today's your lucky day!",
    "Who wants to become a bullet sponge?",
    "This cannon is now canon!\n(to this universe)",
    "Why is there even a slider\nin the first place?",
    "h",
    "PanzerShrek.\nWhy shrek though?",
    "HEAT is soon to come.\nJust need to steal some documents first.",
    "SplashText.txt",
    "Please, not the 1000mm HE!",
    "Previous splash was lying.",
    "owo",
    "I like bullets",
    "All jokes and games until the projectile\nglitches right through your armor.",
    "let me out let me out let me out let me out let me out let me out let me out let me out let me out let me out let me out\n  let me out let me out this is a joke btw let me out let me out let me out let me out let me out let me out let me out let me out\n let me out let me out let me out let me out let me out let me out let me out let me out let me out let me out let me out\n",
    "What's the agenda for today?",
    "This is a false sentence.\n(POWERED BY CAPTCHA)",
    "Artificial Intelligence?\nNah, I prefer natural stupidity",
    "Fully organic!",
    "!11?41??!1!",
    "LEROY JENKINS",
    "Ferrium was here",
    "...but nobody came",
    "Undertale, amiright?",
    "No italic?\nNo bold either?\nThis sucks on ice.",
    "THINK FAST CHUKLENUTS",
    "#e81416r#ffa500a#faeb36i#79c314n#487de7b#4b369do#70369dw #e81416t#ffa500o#faeb36a#79c314s#487de7t#4b369de#70369dr",
    "Mr. President, the towers have been tomfoolered",
    "This splash screen may or may not\ncontain offensive jokes.",
    "www.youtube.com/watch?v=8ybW48rKBME",
    ":trollface:",
    "In my medical opinion?\nYOU'RE DEAD!",
    "It is good day to be\nNOT\nDEAD!",
    "My condolences to your -less than-\nfullHD monitor text scaling",
    "Make the tank you wish\nto see in real life!",
    "Totally not War Thunder advertisement",
    "Wuh oh",
    "Make this a splash pls",
    "500mm BESH hits different at 3am",
    "HE moment",
    "Hey, my caliber is up here!",
    "How do you pronounce Donity_Qramixy?",
    "Ferrium was Ferry before.\nI changed it because it was too similar to Furry.\nNo hate though",
    "Ferrarium\nwroom wroom mothafaka",
    "I-It's to big!\n>=<",
    "I may be offensive..\nBut I do love yall",
    "No HE in the building!",
    "hehe he go boom",
    "APHE actually works.\n(It fried my code AND my brain)",
    "-Insert rickroll here-",
    "What does the tank say?",
    "You've been APFSDS'd",
    "Oh boy, i sure do hope\nthat no flying piece of metal\n ruins my day today!",
    "Come back later,\nand maybe I will tell you a story?",
    "Exotic butters",
    "Go play Voices in the Void.\nIt's FREE",
    "Roblox Cursed Tank Simulator, War Thunder...\nCouldn't this mod be more original?",
    "Water gun",
    "Be careful with recoil",
    "64th splash!",
    "Go play War Thunder!",
    "Scrap Mechanic sux",
    "Yeah yeah, Logic (the modder)..\nI know you're here.",
    "Teh cannns ar dangerus!",
    "Waiter, waiter!\nMore lua hooks please!",
    "English wasn't my first language,\nEngrish was",
    "[REDACTED]",
    "My monitor fell",
    "emty",
    "Previous splash was telling the truth!",
    "You unboxed a #4b369dRare!"
}
